##Example Github Action for building


#name: Docker Build
#
#on:
#  push:
#    tags:
#      - '*-RC'  # Trigger the workflow when a tag like v1.0, v2.5, etc., is pushed to the main branch
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check Out Repo
#        uses: actions/checkout@v4.1.1
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3.0.0
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v3.0.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Extract tag name
#        id: tag_name
#        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
#
#      - name: Build and Push Docker Image
#        uses: docker/build-push-action@v5.1.0
#        with:
#          context: .
#          file: ./docker/spring/Dockerfile
#          push: true
#          tags: |
#            MY_REPO/MY_CONTAINER:latest
#            MY_REPO/MY_CONTAINER:${{ env.TAG_NAME }}
#          build-args: VERSION=${{ env.TAG_NAME }}
